### PR TITLE
Deprecate CentOS 7

### LINKED ISSUE #888: yq no longer installed via metal3-dev-env
Installer fails when executing PIP to build more-itertools required by yq.

Python more-itertools are now at version 8.1 which is python 3 only.

The last version usable in a 2.x environment is 5.0.

if 5.0 is already installed on the host manually (by pulling the relevant release from github and building it locally), the installer succeeds.

### PR DESCRIPTION
**Pull request by russellb**
Most people have already moved to CentOS 8 or RHEL 8 at this point.
Let's give one last very clear warning that CentOS 7 is going away,
and then a bit later we can drop all related code for CentOS 7.

Closes #888

### CODE REVIEW

File: common.sh [hunk 1]
```diff
@@ -236,8 +236,28 @@ fi
 # Check CentOS version
 VER=$(awk -F= '/^VERSION_ID=/ { print $2 }' /etc/os-release | tr -d '"' | cut -f1 -d'.')
 if [[ ${VER} -ne 7 ]] && [[ ${VER} -ne 8 ]]; then
-  echo "Required CentOS 7 / RHEL 7 / RHEL 8"
-  exit 1
+  if [[ ${VER} -eq 7 ]] && [[ "${ALLOW_CENTOS7}" -ne "yes" ]]; then
```
Comment (stbenjam) [inline common.sh]: Does this work? The if statement above on L238 is `if [[ ${VER} -ne 7 ]] && [[ ${VER} -ne 8 ]]`, so I think you won't get to this one on CentOS 7

Comment (russellb) [reply common.sh]: sorry .. obviously did this way too fast

**Comment by stbenjam** [comment]
LGTM now, just want CI to double check

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1692/
