### PR TITLE
Drop the use of custom KNI release images. 

### LINKED ISSUE #724: Bump release version to 4.2.0-0.ci-2019-08-06-190740 (or later)
**Describe the bug**
There is a bug in the OCP console that has been fixed recently https://github.com/openshift/console/pull/2255 and it would be nice to have it in order to show the object storage dashboard metrics.

**To Reproduce**

**Expected/observed behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by stbenjam**
fixes #724

### CODE REVIEW

**Comment by metal3ci** [comment]
Build ABORTED, see build http://10.8.144.11:8080/job/dev-tools/1004/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1005/

**Comment by stbenjam** [comment]
Looks like we're hitting https://github.com/openshift/baremetal-runtimecfg/issues/15

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1009/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1011/

**Comment by stbenjam** [comment]
Looks like some of the Ironic stuff was moved into the MAO: https://github.com/openshift/machine-api-operator/blob/master/pkg/operator/baremetal_pod.go

machine-api fails to come up during install now:

```
[root@dell-r730-021 dev-scripts]# oc get clusteroperator machine-api -o=jsonpath='{range .status.conditions[*]}{.type}{" "}{.status}{" "}{.message}{"\n"}{end}'

Progressing False 

Available True 

Degraded True Failed when progressing towards operator: 4.2.0-0.ci-2019-08-08-094456-kni.0 because Deployment.apps "metal3" is invalid: [spec.template.spec.containers[1].volumeMounts[0].name: Not found: "metal3-shared", spec.template.spec.containers[2].volumeMounts[0].name: Not found: "metal3-shared", spec.template.spec.containers[3].volumeMounts[0].name: Not found: "metal3-shared", spec.template.spec.containers[4].volumeMounts[0].name: Not found: "metal3-shared", spec.template.spec.containers[5].volumeMounts[0].name: Not found: "metal3-shared", spec.template.spec.containers[6].volumeMounts[0].name: Not found: "metal3-shared", spec.template.spec.containers[7].volumeMounts[0].name: Not found: "metal3-shared", spec.template.spec.initContainers[0].volumeMounts[0].name: Not found: "metal3-shared", spec.template.spec.initContainers[1].volumeMounts[0].name: Not found: "metal3-shared"]

Upgradeable True 

[root@dell-r730-021 dev-scripts]# oc get clusteroperator machine-api -o=jsonpath='{range .status.conditions[*]}{.type}{" "}{.status}{" "}{.message}{"\n"}{end}'

Progressing False 

Available True 

Degraded True Failed when progressing towards operator: 4.2.0-0.ci-2019-08-08-094456-kni.0 because Deployment.apps "metal3" is invalid: [spec.template.spec.containers[1].volumeMounts[0].name: Not found: "metal3-shared", spec.template.spec.containers[2].volumeMounts[0].name: Not found: "metal3-shared", spec.template.spec.containers[3].volumeMounts[0].name: Not found: "metal3-shared", spec.template.spec.containers[4].volumeMounts[0].name: Not found: "metal3-shared", spec.template.spec.containers[5].volumeMounts[0].name: Not found: "metal3-shared", spec.template.spec.containers[6].volumeMounts[0].name: Not found: "metal3-shared", spec.template.spec.containers[7].volumeMounts[0].name: Not found: "metal3-shared", spec.template.spec.initContainers[0].volumeMounts[0].name: Not found: "metal3-shared", spec.template.spec.initContainers[1].volumeMounts[0].name: Not found: "metal3-shared"]

Upgradeable True 
```

@sadasu mentioned we need to create the metal3-shared volume in dev-scripts.  Not sure how exactly to do that, I tried this but it didn't work:

```

[root@dell-r730-021 dev-scripts]# cat assets/templates/91_metal3-shared-volume.yaml 

kind: PersistentVolume

apiVersion: v1

metadata:

  name: metal3-shared

  labels:

    type: local

spec:

  capacity:

    storage: 10Gi

  accessModes:

    - ReadWriteMany

  hostPath:

    path: "/shared"

[root@dell-r730-021 dev-scripts]# oc get pv

NAME            CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM   STORAGECLASS   REASON   AGE

metal3-shared   10Gi       RWX            Retain           Available                                   6m43s
```

**Comment by stbenjam** [comment]
As a rule we shouldn't be adding more tech debt to dev-scripts, can the MAO create this volume?  If it's too late due to 4.2 freeze, (1) I need to know what changes we need to dev-scripts to make it work, and (2) an issue tracking the volume creation in the appropriate place (MAO? installer?)

This is currently blocking us going to a new release.

**Comment by sadasu** [comment]
I am currently looking at how this shared volume can be created in MAO. I agree that this should not be tech debt against dev-scripts.

**Comment by stbenjam** [comment]
Thanks!  https://github.com/openshift/machine-api-operator/pull/373 should fix this, I'll build a new KNI release when that's merged and in a CI build.

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1025/

**Comment by e-minguez** [comment]
The 24h bug https://bugzilla.redhat.com/show_bug.cgi?id=1736800 seems to be fixed in 4.2.0-0.nightly-2019-08-09-000333 so hopefully we can use that (or later)

**Comment by stbenjam** [comment]
Note, this is currently blocked by https://github.com/openshift/machine-api-operator/pull/374.  Need that to get in before install will complete successsfully

**Comment by hardys** [comment]
I re-tested with `registry.svc.ci.openshift.org/ocp/release:4.1.0-0.ci-2019-08-13-013332` which I think should contain the MAO fixes above, but it seems we still need a way to create the missing configmap for the MAO baremetal-operator integration:

```
$ oc describe pod --namespace openshift-machine-api metal3-7557d6d788-6bqfr | grep Failed
  Warning  Failed     69m (x8 over 70m)    kubelet, master-1  Error: configmaps "metal3-config" not found
```

I know @imain and @sadasu have been looking into the final solution there ref https://github.com/openshift/installer/pull/2149 but to make this work now I think we'll need to create that configmap in dev-scripts?

**Comment by hardys** [comment]
Or, rather figure out how we can apply the configmap from `08_deploy_bmo.sh` during `06_create_cluster.sh` so that the deploy doesn't time out on the MAO

**Comment by stbenjam** [comment]
We can maybe drop it in the assets directory for now

**Comment by hardys** [comment]
> We can maybe drop it in the assets directory for now

Yeah good point, the other issue is we don't have a way to kill the dnsmasq on the host after the host which is also done in the 08 script (this will be resolved when we move to bootstrap hosted ironic).

In practice that's probably not a problem, since we don't create the worker CRs inside the installer (yet) and if we merge https://github.com/openshift-metal3/dev-scripts/pull/715 workers can be explictly handled as a post-deploy task.

**Comment by hardys** [comment]
FYI my test branch is https://github.com/hardys/dev-scripts/tree/pr_726 still WIP but wanted to ensure we don't duplicate too much effort :)

File: utils.sh [hunk 1]
```diff
@@ -8,6 +8,11 @@ function generate_assets() {
       echo "Templating ${file} to assets/generated/${file}"
       cp assets/{templates,generated}/${file}
 
+      # FIXME: TEMPLATING FOR METAL3 CONFIGMAP
```
Comment (hardys) [inline utils.sh]: We need to copy the template before sedding I think - see my branch where I added a function that does that, one thing I'm not yet clear on is how we make that configmap appear in the openshift-machine-api namespace via a manifest, vs the --namespace arg on the CLI (I guess we can specify that context in the manifest, but not familiar with the exact syntax yet)

Comment (stbenjam) [reply utils.sh]: Ah got it, I don't want to duplicate effort since it seems like you're further along.

I think you can add `namespace` to metadata, at least according to https://unofficial-kubernetes.readthedocs.io/en/latest/tasks/configure-pod-container/configmap/:


```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: example-config
  namespace: default
```

Comment (hardys) [reply utils.sh]: Ack thanks, makes sense - updated my branch and re-testing now

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1034/

**Comment by stbenjam** [comment]
I've incorporated @hardys's branch here, metal3 pod is failing to come up now:

```
[root@dell-r730-021 dev-scripts]# oc logs -n openshift-machine-api pod/metal3-7557d6d788-cfdt6
Error from server (BadRequest): a container name must be specified for pod metal3-7557d6d788-cfdt6, choose one of: [metal3-baremetal-operator metal3-dnsmasq metal3-mariadb metal3-httpd metal3-ironic-conductor metal3-ironic-api metal3-ironic-exporter metal3-ironic-inspector metal3-static-ip-manager] or one of the init containers: [metal3-ipa-downloader metal3-rhcos-downloader metal3-static-ip-set]
```

**Comment by stbenjam** [comment]
metal3 pod is still in CrashLoopBackOff

```
[root@dell-r730-021 dev-scripts]# oc get all -n openshift-machine-api
NAME                                              READY   STATUS                  RESTARTS   AGE
pod/cluster-autoscaler-operator-9479cd49f-v77lm   1/1     Running                 0          16m
pod/machine-api-controllers-5d9455dc4f-q2cz8      3/3     Running                 0          30m
pod/machine-api-operator-cc7487f6f-m4jsw          1/1     Running                 1          31m
pod/metal3-7557d6d788-cfdt6                       0/9     Init:CrashLoopBackOff   8          30m

NAME                                  TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)            AGE
service/cluster-autoscaler-operator   ClusterIP   172.30.254.252   <none>        443/TCP,8080/TCP   32m
service/machine-api-operator          ClusterIP   172.30.164.45    <none>        8080/TCP           31m

NAME                                          READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/cluster-autoscaler-operator   1/1     1            1           16m
deployment.apps/machine-api-controllers       1/1     1            1           30m
deployment.apps/machine-api-operator          1/1     1            1           31m
deployment.apps/metal3                        0/1     1            0           30m

NAME                                                    DESIRED   CURRENT   READY   AGE
replicaset.apps/cluster-autoscaler-operator-9479cd49f   1         1         1       16m
replicaset.apps/machine-api-controllers-5d9455dc4f      1         1         1       30m
replicaset.apps/machine-api-operator-cc7487f6f          1         1         1       31m
replicaset.apps/metal3-7557d6d788                       1         1         0       30m
```

It looks like it might be related to metal3-static-ip-set:

```
[root@dell-r730-021 dev-scripts]# oc logs -n openshift-machine-api pod/metal3-7557d6d788-cfdt6  --container=metal3-static-ip-set
+ '[' -z ens3 ']'
+ '[' -z 172.22.0.3/24 ']'
+ /usr/sbin/ip address flush dev ens3
Device "ens3" does not exist.
```

All my masters do have ens3 devices though...

**Comment by russellb** [comment]
That would happen if that container isn't run with host networking

**Comment by stbenjam** [comment]
https://github.com/openshift/machine-api-operator/pull/377

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1035/

**Comment by stbenjam** [comment]
MAO PR is merged, going to test again. However, ironic on bootstrap has also merged so I've pulled in https://github.com/openshift-metal3/dev-scripts/pull/642, too.

**Comment by metal3ci** [comment]
Build ABORTED, see build http://10.8.144.11:8080/job/dev-tools/1038/

**Comment by stbenjam** [comment]
It is still failing for me, and I see no evidence the pod is using hostNetwork. It does not appear in the pod YAML at all.

https://github.com/openshift/machine-api-operator/blob/master/vendor/k8s.io/api/core/v1/types.go#L2876 indicates that maybe we must also explicitly list every port we need from that pod? I could use some help figuring this out, I haven't been able to deploy a custom MAO either, so really hard to iterate and test.

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1039/

**Comment by russellb** [comment]
I suggest we accept that the baremetal-operator is temporarily broken, and change CI to pass without it working.  That will unblock updates while we continue to fix the issues with it.

**Comment by stbenjam** [comment]
Russell noticed in my env, it was running an Origin build instead of a CI one.   Overriding the release image has been broken for a while, and the version I tested with yesterday did not have the MAO HostNetwork fix.  Hopefully once https://github.com/openshift/installer/pull/2217 we can kick off our CI again and things might look better. Running a local test now.

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1040/

**Comment by metal3ci** [comment]
Build ABORTED, see build http://10.8.144.11:8080/job/dev-tools/1042/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1043/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1044/

File: utils.sh [hunk 2]
```diff
@@ -189,4 +189,6 @@ function bmo_config_map {
     sed -i "s#cache_url: \"http://192.168.111.1/images\"#cache_url: \"http://${BAREMETAL_IP}/images\"#" ocp/deploy/metal3-config.yaml
     
     cp ocp/deploy/metal3-config.yaml assets/generated/99_metal3-config.yaml
```
Comment (hardys) [inline utils.sh]: We also need to add the openshift-machine-api namespace to the `metal3-config.yaml` in the metadata, and remove the `operator_ironic.yaml`

**Comment by russellb** [comment]
I looked at the metal3 deployment under the machine-api-operator some more yesterday and put up a few more patches to address some issues:

* https://github.com/openshift/ironic-inspector-image/pull/13
* https://github.com/openshift/machine-api-operator/pull/380
* https://github.com/openshift/machine-api-operator/pull/381

File: utils.sh (hunk 2 above)
Comment (russellb) [reply utils.sh]: metal3-config.yaml has the namespace, i'll drop operator_ironic.yaml

**Comment by metal3ci** [comment]
Build ABORTED, see build http://10.8.144.11:8080/job/dev-tools/1046/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1047/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1048/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1049/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1050/

**Comment by russellb** [comment]
I expect us to merge this without fully fixing the baremetal-operator pod, so I've opened an issue to track the remaining work to fix that: https://github.com/openshift-metal3/dev-scripts/issues/739

**Comment by russellb** [comment]
I see in this latest CI run that our release isn't being used ...

`Aug 15 19:39:52 |  level=debug msg="Still waiting for the cluster to initialize: Working towards 4.2.0-0.okd-2019-08-15-190342"`

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1051/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1052/

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1053/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1054/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1055/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1056/

**Comment by metal3ci** [comment]
Build ABORTED, see build http://10.8.144.11:8080/job/dev-tools/1057/

**Comment by metal3ci** [comment]
Build ABORTED, see build http://10.8.144.11:8080/job/dev-tools/1058/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1059/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1060/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1061/

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1062/
